# Generated by Django 4.1.3 on 2022-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_juego_alter_jugador_name_juego_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
