# Generated by Django 4.1.3 on 2022-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
