# Generated by Django 4.1.3 on 2022-12-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_categoria_juego_juego_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='URLGame',
            field=models.TextField(null=True),
        ),
    ]
